# Generated by Django 2.2 on 2020-02-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_pro_pic.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
