# Generated by Django 2.2 on 2020-02-25 08:00

from django.db import migrations
# import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200223_2051'),
    ]

    # operations = [
    #     # migrations.AlterField(
    #     #     model_name='post',
    #     #     name='overview',
    #     #     # field=tinymce.models.HTMLField(),
    #     # ),
    # ]
