# Generated by Django 2.2 on 2020-02-29 03:46

from django.db import migrations
# import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200226_2202'),
    ]

    # operations = [
    #     # migrations.AlterField(
    #     #     model_name='post',
    #     #     name='overview',
    #     #     # field=tinymce.models.HTMLField(),
    #     # ),
    # ]
