# Generated by Django 2.2 on 2020-02-29 06:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200229_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
